var team1 = { "Team_name" : "Go Corona",
                member:["Layo",
                        "Arjun",
                        "Arya",
                        "Jeffin",
                        "Christeena",
                        "Suby",
                        "Aswathy"],
                badge1:["Captain","Vice Captain","Vice Captain"],
                badge2:["0","0","0","0","0","0","0"]
            };
                        
var team2 = { "Team_name" : "Annamma's Army",
                        member:["Sneha Anna",
                        "Mishab ",
                        "Navneet",
                        "Likitha",
                        "Abhinand",
                        "Nimisha",
                        "Sreedevi"]};
var team3 = { "Team_name" : "Veetil Iri",
                        member:["Nisha ",
                        "Melvin",
                        "Pavithra",
                        "Shishir",
                        "Sneha Sara",
                        "Devika ",
                        "Bipin",
                        "Renz"]};
var team4 = { "Team_name" : "Nammal Powlikyum",
                        member:["Shuhaib ",
                        "Ananthu ",
                        "Revathy",
                        "Reenu",
                        "Sandra",
                        "Aparna",
                        "Minhaj"]};